version = 0.1
[default.deploy.parameters]
stack_name = "lambda-curso-stack"
resolve_s3 = true
s3_prefix = "lambda-curso-stack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "DBHost=\"aws-1-us-east-2.pooler.supabase.com\" DBName=\"postgres\" DBUser=\"postgres.sgurubkezsrbapgcyfur\" DBPassword=\"xWVmrWM91FVKyqh8\""
image_repositories = []
